name: Go React Starter | Build

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build-

      - name: Check Go Version
        run: go version

      - name: Run Server Build
        run: |
          if ! go build -tags netgo -ldflags '-s -w' -o app; then
            echo "Build failed, please check the logs."
            exit 1
          fi

      - name: Upload Server Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-app
          path: app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Client Dependencies
        run: |
          cd client
          npm ci --cache .npm --prefer-offline

      - name: Run Client Build
        run: |
          cd client
          npm run build

      - name: Upload Client Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: app
